/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bd.Conexion;
import entidades.Cliente;
import entidades.Producto;
import entidades.Servicio;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class PanelOpciones extends javax.swing.JPanel {

    DefaultListModel modCliente = new DefaultListModel();
    DefaultListModel modTelefonos = new DefaultListModel();
    TableModel modCarrito = new TableModel(new String[]{"Piezas", "Producto", "P/U", "pago"}, 0);
    DefaultComboBoxModel modServicios = new DefaultComboBoxModel();
    DefaultComboBoxModel modInicio = new DefaultComboBoxModel();
    DefaultComboBoxModel modDuracion = new DefaultComboBoxModel();
    DefaultComboBoxModel modAccesorio = new DefaultComboBoxModel();
    DefaultComboBoxModel modDispAccesorio = new DefaultComboBoxModel();
    DefaultComboBoxModel modAlimento = new DefaultComboBoxModel();
    DefaultComboBoxModel modDispAlimento = new DefaultComboBoxModel();

    /**
     * Creates new form PanelCompras
     */
    public PanelOpciones() {
        initComponents();
        cargarClientes();
        cargaArticulos();
        cargaServicios();
    }

    private void cargarClientes() {
        try {
            Conexion cn = new Conexion();
            ArrayList<Cliente> tabla = cn.getClientes();
            modCliente.removeAllElements();
            for (Cliente cliente : tabla) {
                modCliente.addElement(cliente);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erorr en bd");
        }
    }

    private void cargaArticulos() {
        try {
            Conexion cn = new Conexion();
            ArrayList<Producto> tabla = cn.getAccesorios();
            modAccesorio.removeAllElements();
            modAccesorio.addElement(new Producto(-1, "Seleccione Accesorio", -1, -1, "Accesorio"));
            for (Producto producto : tabla) {
                modAccesorio.addElement(producto);
            }
            ArrayList<Producto> tabla2 = cn.getAlimentos();
            modAlimento.removeAllElements();
            modAlimento.addElement(new Producto(-1, "Seleccione Alimento", -1, -1, "Alimento"));
            for (Producto producto : tabla2) {
                modAlimento.addElement(producto);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erorr en bd");
        }

    }

    private void cargaServicios() {
        try {
            Conexion cn = new Conexion();
            ArrayList<Servicio> tabla = cn.getServicios();
            for (Servicio servicio : tabla) {
                modServicios.addElement(servicio);
            }
            jComboBox2.setModel(modInicio);
            for (int i = 9; i < 16; i++) {
                modInicio.addElement(new Time(i, 0, 0));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erorr en bd");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boxServicios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser(new Date(120,3,10));
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        labelCosto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCarrito = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        totalCompra = new javax.swing.JLabel();
        boxAccesorios = new javax.swing.JComboBox<>();
        boxAlimentos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        boxCantidadAccesorio = new javax.swing.JComboBox<>();
        addAccesorio = new javax.swing.JButton();
        addAlimento = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        boxCantidadAlimentos = new javax.swing.JComboBox<>();
        labeldispAccesorios = new javax.swing.JLabel();
        labeldispAlimentos = new javax.swing.JLabel();
        costoAcc = new javax.swing.JLabel();
        costoAlim = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelNombreCompleto = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        listaUsuarios.setModel(this.modCliente);
        listaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaUsuariosMouseClicked(evt);
            }
        });
        listaUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaUsuariosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listaUsuarios);

        jLabel3.setText("lista de clentes:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar cita"));

        jLabel2.setText("Motivo del servicio:");

        boxServicios.setModel(this.modServicios);
        boxServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxServiciosActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha del servicio:");

        jLabel4.setText("Duracion(hrs:min:seg):");

        jComboBox3.setModel(this.modDuracion);

        labelCosto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelCosto.setText("Costo:");

        jButton1.setText("Confirmar cita");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Hora del servicio:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxServicios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(255, 255, 255))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(labelCosto)
                        .addGap(141, 141, 141))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(253, 253, 253))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCosto))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Comprar Accesorios/Alimento"));

        tableCarrito.setModel(this.modCarrito);
        jScrollPane2.setViewportView(tableCarrito);

        jButton2.setText("Confirmar compra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        totalCompra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        boxAccesorios.setModel(this.modAccesorio);
        boxAccesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAccesoriosActionPerformed(evt);
            }
        });

        boxAlimentos.setModel(this.modAlimento);
        boxAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlimentosActionPerformed(evt);
            }
        });

        jLabel7.setText("Cantidad:");

        boxCantidadAccesorio.setModel(this.modDispAccesorio);

        addAccesorio.setText("añadir Accesorio");
        addAccesorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccesorioActionPerformed(evt);
            }
        });

        addAlimento.setText("añadir alimento");
        addAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlimentoActionPerformed(evt);
            }
        });

        jLabel8.setText("Cantidad:");

        boxCantidadAlimentos.setModel(this.modDispAlimento);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(boxAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoAcc))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(boxAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoAlim)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxCantidadAccesorio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeldispAccesorios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addAccesorio))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxCantidadAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labeldispAlimentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addAlimento)))
                        .addGap(39, 39, 39)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoAcc))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(boxCantidadAccesorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labeldispAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addAccesorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoAlim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(boxCantidadAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labeldispAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addAlimento, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(totalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del cliente"));

        labelNombreCompleto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        actualizar.setText("actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(actualizar)
                                .addGap(0, 34, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaUsuariosMouseClicked
        Cliente cliente = (Cliente) listaUsuarios.getSelectedValue();
        if (cliente != null) {
            labelNombreCompleto.setText(cliente.toString());
        }
    }//GEN-LAST:event_listaUsuariosMouseClicked

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try {
            Conexion cn = new Conexion();
            ArrayList<Cliente> tabla = cn.getClientes();
            modCliente.removeAllElements();
            for (Cliente cliente : tabla) {
                modCliente.addElement(cliente);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erorr en bd");
        }

    }//GEN-LAST:event_actualizarActionPerformed

    private void boxServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxServiciosActionPerformed
        Servicio s = (Servicio) boxServicios.getSelectedItem();
        labelCosto.setText("Costo:$" + Float.toString(s.getCosto()) + " MXN");
        modDuracion.removeAllElements();
        if (s.getDuracion() == null) {
            jLabel4.setText("Duracion(hrs:min:seg):");
            for (int i = 1; i < 7; i++) {
                modDuracion.addElement(new Time(i, 0, 0));
            }
            jComboBox3.setVisible(true);
            jComboBox3.setEnabled(true);
        } else {
            jLabel4.setText("Duracion(hrs:min:seg):  " + s.getDuracion().toString());
            modDuracion.addElement(s.getDuracion());
            jComboBox3.setVisible(false);
            jComboBox3.setEnabled(false);
        }
    }//GEN-LAST:event_boxServiciosActionPerformed

    private void listaUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaUsuariosKeyPressed
        // TODO add your handling code here:
        Cliente cliente = (Cliente) listaUsuarios.getSelectedValue();
        if (cliente != null) {
            labelNombreCompleto.setText(cliente.toString());
        }
    }//GEN-LAST:event_listaUsuariosKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date temp = jDateChooser1.getDate();
        Time temp2 = (Time) jComboBox2.getSelectedItem();
        Time temp3 = (Time) jComboBox3.getSelectedItem();
        Timestamp inicio = new Timestamp(temp.getYear(), temp.getMonth(), temp.getDate(), temp2.getHours(), temp2.getMinutes(), temp2.getSeconds(), 0);
        Timestamp fin = new Timestamp(temp.getYear(), temp.getMonth(), temp.getDate(),
                temp2.getHours() + temp3.getHours(), temp2.getMinutes() + temp3.getMinutes(), temp2.getSeconds() + temp3.getSeconds(), 0);
        try {
            Cliente c = (Cliente) listaUsuarios.getSelectedValue();
            if (c != null) {
                Conexion cn = new Conexion();
                int id = cn.insertarCita(inicio, fin, c.getUsuario(), ((Servicio) boxServicios.getSelectedItem()).getIdServicio());
                JOptionPane.showMessageDialog(this, "Cita generada:\n id de la cita:" + id + "\n fecha de la cita:" + inicio + "\n servicio:" + ((Servicio) boxServicios.getSelectedItem()).getMotivo());
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione usuario");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erorr en bd");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlimentosActionPerformed
        // TODO add your handling code here:
        Producto pd = (Producto) modAlimento.getSelectedItem();
        modDispAlimento.removeAllElements();
        if (pd != null) {
            if (pd.getDisponibles() == -1) {
                addAlimento.setVisible(false);
                addAlimento.setEnabled(false);
                labeldispAlimentos.setText("");
            } else {
                costoAlim.setText("Precio:$" + pd.getPrecio() + " MXN");
                if (pd.getDisponibles() == 0) {
                    addAlimento.setVisible(false);
                    addAlimento.setEnabled(false);
                    labeldispAlimentos.setForeground(Color.red);
                    labeldispAlimentos.setText("no disponible");
                } else {
                    addAlimento.setVisible(true);
                    addAlimento.setEnabled(true);
                    labeldispAlimentos.setForeground(Color.green);
                    labeldispAlimentos.setText("disponible");
                    for (int i = 1; i <= pd.getDisponibles(); i++) {
                        modDispAlimento.addElement(i);
                    }
                }
            }
        }
    }//GEN-LAST:event_boxAlimentosActionPerformed

    private void boxAccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAccesoriosActionPerformed
        // TODO add your handling code here:
        Producto pd = (Producto) modAccesorio.getSelectedItem();
        modDispAccesorio.removeAllElements();
        if (pd != null) {
            if (pd.getDisponibles() == -1) {
                addAccesorio.setVisible(false);
                addAccesorio.setEnabled(false);
                labeldispAccesorios.setText("");
            } else {
                costoAcc.setText("Precio:$" + pd.getPrecio() + " MXN");
                if (pd.getDisponibles() == 0) {
                    addAccesorio.setVisible(false);
                    addAccesorio.setEnabled(false);
                    labeldispAccesorios.setForeground(Color.red);
                    labeldispAccesorios.setText("no disponible");
                } else {
                    addAccesorio.setVisible(true);
                    addAccesorio.setEnabled(true);
                    labeldispAccesorios.setForeground(Color.green);
                    labeldispAccesorios.setText("disponible");
                    for (int i = 1; i <= pd.getDisponibles(); i++) {
                        modDispAccesorio.addElement(i);
                    }
                }
            }
        }
    }//GEN-LAST:event_boxAccesoriosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            Cliente c = (Cliente) listaUsuarios.getSelectedValue();
            if (c != null) {
                Conexion cn = new Conexion();
                int filas=modCarrito.getRowCount();
                for (int i = 0; i <filas ; i++) {
                    int prod = ((Producto) modCarrito.getValueAt(0, 1)).getIdProd();
                    float cant = Float.parseFloat(modCarrito.getValueAt(0, 0).toString());
                    modCarrito.removeRow(0);
                    cn.insertarCompra(c.getUsuario(), prod, cant);
                }
                JOptionPane.showMessageDialog(this, "Compra Realizada");
                cargaArticulos();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione usuario");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "erorr en bd");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addAccesorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccesorioActionPerformed
        // TODO add your handling code here:
        Producto pd = (Producto) boxAccesorios.getSelectedItem();
        Float cantidad = Float.parseFloat(boxCantidadAccesorio.getSelectedItem().toString());

        modCarrito.addRow(new Object[]{cantidad, pd, pd.getPrecio(), pd.getPrecio() * cantidad});
        float total = 0.00f;
        for (int i = 0; i < modCarrito.getRowCount(); i++) {
            total += Float.parseFloat(modCarrito.getValueAt(i, 3).toString());
        }
        totalCompra.setText("Total:$" + total + " MXN");

    }//GEN-LAST:event_addAccesorioActionPerformed

    private void addAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlimentoActionPerformed
        // TODO add your handling code here:
        Producto pd = (Producto) boxAlimentos.getSelectedItem();
        Float cantidad = Float.parseFloat(boxCantidadAlimentos.getSelectedItem().toString());
        modCarrito.addRow(new Object[]{cantidad, pd, pd.getPrecio(), pd.getPrecio() * cantidad});
        float total = 0.00f;
        for (int i = 0; i < modCarrito.getRowCount(); i++) {
            total += Float.parseFloat(modCarrito.getValueAt(i, 3).toString());
        }
        totalCompra.setText("Total:$" + total + " MXN");
    }//GEN-LAST:event_addAlimentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton addAccesorio;
    private javax.swing.JButton addAlimento;
    private javax.swing.JComboBox<Producto> boxAccesorios;
    private javax.swing.JComboBox<String> boxAlimentos;
    private javax.swing.JComboBox<Integer> boxCantidadAccesorio;
    private javax.swing.JComboBox<String> boxCantidadAlimentos;
    private javax.swing.JComboBox<String> boxServicios;
    private javax.swing.JLabel costoAcc;
    private javax.swing.JLabel costoAlim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCosto;
    private javax.swing.JLabel labelNombreCompleto;
    private javax.swing.JLabel labeldispAccesorios;
    private javax.swing.JLabel labeldispAlimentos;
    private javax.swing.JList listaUsuarios;
    private javax.swing.JTable tableCarrito;
    private javax.swing.JLabel totalCompra;
    // End of variables declaration//GEN-END:variables
}

class TableModel extends DefaultTableModel {

    public TableModel(Object[] ids, int cont) {
        super(ids, cont);
    }

    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }

}
